server:
  port: 8881
spring:
  application:
    name: springcloud-user
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
eureka:
  client:
    serviceUrl:
      defaultZone: http://x123:x123@127.0.0.1:8761/eureka/,http://x123:x123@127.0.0.1:8762/eureka/
    healthcheck:
      enabled: true
  instance:
    prefer-ip-address: true
    instanceId: ${spring.cloud.client.ip-address}:${server.port}[${spring.application.name}]
info:
  name: ${spring.application.name}
  address: ${spring.cloud.client.ip-address}
  port: ${server.port}