server:
  port: 9999
spring:
  application:
    name: springcloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/xiaqiao/config-repo
          #github默认分支由master改为main
          default-label: main