#server:
#  port: 8761
#eureka:
#  server:
#    #renews和renews threshold的比值 默认0.85
#    renewal-percent-threshold: 0.45
#  client:
#    register-with-eureka: false
#    fetch-registry: false
#spring:
#  security:
#    user:
#      name: x123
#      password: x123